[package]
name = "shiro_exploit" #改这个
version = "0.1.0"
edition = "2021"
authors = ["Kali-Team <root@kali-team.cn>"]
include = ["LICENSE", "Cargo.toml", "src/**/*.rs"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["."]

#https://github.com/johnthagen/min-sized-rust
[profile.release]
opt-level = "z"     # Optimize for size.
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.

[profile.dev.package."*"]
opt-level = 3
[profile.test]
opt-level = 3
lto = "thin"

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3


[dependencies]
argh = "0.1.8"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11.6", features = [
    "native-tls",
    "socks",
    "blocking",
    "gzip",
    "cookies",
] }
anyhow = "1"
tokio = { version = "1.19.2", default-features = false, features = [
    "process",
    "macros",
] }
encoding_rs = "0.8.28"
mime = "0.3.16"
select = "0.6.0"
once_cell = "1.10.0"
ysoserial_rs = { git = "https://github.com/emo-cat/ysoserial_rs" }
uuid = { version = "1.2", features = ["serde", "v1", "v3", "v4"] }
futures = { version = "0.3", features = ["compat"] }
prettytable-rs = "0.9.0"